import { test, expect } from '@playwright/test';
test.beforeEach(async ({ page }) => {
  await page.route('https://fireemblemwiki.org/**', route => route.fulfill({ json: { parse: { text: { '*': '<table><tr><td><img src="/portrait.svg" /></td><td><a>Cai</a></td></tr></table>' } } } }));
  await page.route('https://fireemblemwiki.org/portrait.svg', route => route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="80" height="160"><rect width="80" height="160" fill="#617d6f"/></svg>' }));
});
test('core navigation, data table, search, clipboard and layout', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.addInitScript(() => { Object.defineProperty(navigator, 'clipboard', { value: { writeText: async (text: string) => { document.documentElement.dataset.copied = text; } }, configurable: true }); });
  await page.goto('./');
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
  const routeTabs = page.getByRole('tablist', { name: '路线选择' });
  await expect(routeTabs.getByRole('tab')).toHaveCount(4);
  for (const name of ['Dietrich', 'Leda', 'Cai', 'Theodora']) await routeTabs.getByRole('tab', { name: new RegExp(name) }).click();
  await expect(page.getByRole('tab', { name: '核心固定 5' })).toBeVisible();
  await expect(page.locator('.roster-item.kind-fixed')).toHaveCount(5);
  await page.locator('#route-panel').scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath('route-viewport.png') });
  await page.getByRole('tab', { name: '建议主要招募 8' }).click();
  await expect(page.locator('.roster-item.kind-primary').filter({ visible: true })).toHaveCount(8);
  await page.getByRole('tab', { name: '第二版本 / 合流培养 5' }).click();
  await expect(page.locator('.roster-item.kind-merge')).toHaveCount(5);
  await page.getByRole('textbox', { name: '搜索角色' }).fill('Nuzzuo');
  await expect(page.locator('#routes [data-character="nuzzuo"]')).toBeVisible();
  await expect(page.locator('#routes [data-character="nuzzuo"]')).toContainText('S1 / R6 · 3x Iron Bows');
  await page.getByRole('textbox', { name: '搜索角色' }).fill('Creek');
  await expect(page.getByText('没有匹配的角色。')).toBeVisible();
  await page.getByRole('textbox', { name: '搜索角色' }).fill('');
  await page.getByRole('button', { name: '只看合流对象' }).click();
  await expect(page.locator('.roster-item.kind-merge')).toHaveCount(5);
  await page.getByRole('button', { name: '当前分类', exact: true }).click();
  const table = page.locator('#growthTable');
  await expect(table.locator('tbody tr')).toHaveCount(53);
  for (const name of ['头像', '凯伊', '迪托利希', '赛奥朵拉', '蕾达']) await expect(table.getByRole('columnheader', { name, exact: true })).toBeVisible();
  await expect(table.locator('[data-character="nuzzuo"] [data-route="theodora"]')).toHaveText('弓替补');
  await page.getByRole('button', { name: '复制整表（CSV）' }).click();
  await expect(page.getByText('已复制 CSV', { exact: true })).toBeVisible();
  const copied = await page.locator('html').getAttribute('data-copied');
  expect(copied?.split('\r\n')).toHaveLength(54); expect(copied).not.toContain('Eshmel');
  await page.getByRole('button', { name: '复制整表（TSV）' }).click();
  expect(await page.locator('html').getAttribute('data-copied')).toContain('\tHP\tSTR\t');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('planner.png'), fullPage: true });
  expect(errors).toEqual([]);
});
test('double spoiler gate, keyboard cancel, lazy load, re-lock and refresh', async ({ page }) => {
  const spoilerRequests: string[] = []; page.on('request', request => { if (/assets\/spoilers-/.test(request.url())) spoilerRequests.push(request.url()); });
  await page.goto('./');
  await expect(page.locator('body')).not.toContainText('Creek'); expect(spoilerRequests).toHaveLength(0);
  await page.getByRole('button', { name: '查看后期信息', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button', { name: '继续隐藏', exact: true }).click();
  await expect(page.locator('body')).not.toContainText('Creek'); expect(spoilerRequests).toHaveLength(0);
  await page.getByRole('button', { name: '查看后期信息', exact: true }).click(); await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: '查看后期信息', exact: true }).click(); await page.getByRole('button', { name: '确认显示', exact: true }).click();
  await expect(page.locator('.spoiler-content')).toContainText('Creek');
  await expect(page.locator('#growthTable')).toContainText('Eshmel'); expect(spoilerRequests).toHaveLength(1);
  await page.locator('.checkline input').first().check();
  await page.getByRole('button', { name: '重新隐藏剧透' }).click();
  await expect(page.locator('body')).not.toContainText('Creek'); await expect(page.locator('#growthTable')).not.toContainText('Eshmel');
  await page.getByRole('button', { name: '查看后期信息', exact: true }).click(); await page.getByRole('button', { name: '确认显示', exact: true }).click();
  await expect(page.locator('.checkline input').first()).toBeChecked();
  await page.reload(); await expect(page.getByRole('button', { name: '查看后期信息', exact: true })).toBeVisible();
  await expect(page.locator('body')).not.toContainText('Creek');
});
test('legacy theme and progress survive migration, changes and reload', async ({ page }) => {
  await page.goto('./');
  await page.evaluate(() => { localStorage.clear(); localStorage.setItem('fw-theme', 'dark'); localStorage.setItem('fw-planner:unit-cai-primary-古扎岚', '1'); });
  await page.reload(); await expect(page.locator('body')).toHaveClass('dark');
  await page.getByRole('tab', { name: '建议主要招募 8' }).click();
  await expect(page.getByRole('checkbox', { name: '古扎岚已招募' })).toBeChecked();
  await page.getByRole('checkbox', { name: '努佐已招募' }).check();
  await page.reload(); await page.getByRole('tab', { name: '建议主要招募 8' }).click();
  await expect(page.getByRole('checkbox', { name: '努佐已招募' })).toBeChecked();
  await page.getByRole('button', { name: '切换亮色' }).click(); await page.reload();
  await expect(page.locator('body')).not.toHaveClass('dark');
  await page.getByRole('button', { name: '切换深色' }).click(); await page.reload();
  await expect(page.locator('body')).toHaveClass('dark');
  expect(await page.evaluate(() => localStorage.getItem('fw-planner:unit-cai-primary-古扎岚'))).toBe('1');
});
test('Wiki failure and unavailable storage leave the planner usable', async ({ page }) => {
  await page.route('https://fireemblemwiki.org/**', route => route.fulfill({ json: { error: { code: 'unavailable' } } }));
  await page.addInitScript(() => { Storage.prototype.getItem = () => { throw new DOMException('Denied'); }; Storage.prototype.setItem = () => { throw new DOMException('Denied'); }; });
  await page.goto('./');
  await expect(page.getByText('Wiki头像：加载失败，已使用文字徽章')).toBeVisible();
  await page.getByRole('tab', { name: '建议主要招募 8' }).click();
  await page.getByRole('checkbox', { name: '努佐已招募' }).check();
  await expect(page.getByRole('checkbox', { name: '努佐已招募' })).toBeChecked();
  await expect(page.locator('#routes [role="alert"]')).toContainText('无法保存');
  await page.getByRole('button', { name: '切换深色' }).click(); await expect(page.locator('body')).toHaveClass('dark');
});
